trigger:
    on_phrase: panic
    start:
        workflow:
            uri: wss://awh.relaypro.com/wf/panic
            transient: false
        args:
            incident_type: Panic Alert
            targets: bear
            emergency_group: security
            audible_confirmation_for_originator: true

