name: docs

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: 'Configure git'
        run: |
          git config user.name 'Relay Pro builder'
          git config user.email 'info@relaypro.com'

      - name: 'Install mkdocs venv'
        run: make venv

      - name: 'Build mkdocs'
        run: make gh-deploy
